#!/usr/bin/env python3
"""Bundle the catalog and both tools into one dependency-free script.

The catalog is YAML for editing but JSON for shipping, so the bundle needs
nothing but a Python 3.8+ interpreter — no pip, no venv, no repo checkout.
Regenerate with:  python3 tools/bundle.py
"""

from __future__ import annotations

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "dist" / "spacedangers_verify.py"


def strip_module(path: pathlib.Path) -> str:
    """Drop the shebang, module docstring, imports and __main__ guard."""
    src = path.read_text(encoding="utf-8")
    src = re.sub(r'\A(#![^\n]*\n)?("""(?:.|\n)*?"""\n)', "", src, count=1)
    lines = []
    for line in src.splitlines():
        if re.match(r"^(import |from |if __name__)", line):
            break_marker = line.startswith("if __name__")
            if break_marker:
                break
            continue
        lines.append(line)
    return "\n".join(lines)


def main() -> None:
    import yaml

    catalog = yaml.safe_load((ROOT / "catalog" / "sources.yaml").read_text(encoding="utf-8"))
    verify_src = strip_module(ROOT / "tools" / "verify.py")
    rank_src = strip_module(ROOT / "tools" / "rank.py")

    # Both modules define main(); keep them apart.
    verify_src = verify_src.replace("def main() -> int:", "def _verify_main(argv) -> int:")
    rank_src = rank_src.replace("def main() -> int:", "def _rank_main(argv) -> int:")
    for name, src in (("verify", verify_src), ("rank", rank_src)):
        if f"_{name}_main" not in src:
            raise SystemExit(f"bundler could not find main() in tools/{name}.py")
    verify_src = verify_src.replace("args = ap.parse_args()", "args = ap.parse_args(argv)")
    rank_src = rank_src.replace("args = ap.parse_args()", "args = ap.parse_args(argv)")

    # The bundled catalog is a literal, so there is no file to open.
    read_catalog = (
        '    with open(args.catalog, encoding="utf-8") as fh:\n'
        "        catalog = yaml.safe_load(fh)"
    )
    for name in ("verify", "rank"):
        src = verify_src if name == "verify" else rank_src
        if read_catalog not in src:
            raise SystemExit(f"bundler could not find the catalog read in tools/{name}.py")
    verify_src = verify_src.replace(read_catalog, "    catalog = CATALOG")
    rank_src = rank_src.replace(read_catalog, "    catalog = CATALOG")

    header = '''#!/usr/bin/env python3
"""spacedangers — verify every space-hazard data source, then rank what survives.

Standalone: no pip install, no repo checkout, Python 3.8+ and nothing else.

    python3 spacedangers_verify.py

It hits every endpoint in the embedded catalog, checks each response against
the expectations declared for it, scores the sources from what actually
answered, and writes SOURCES.md plus the raw JSON next to itself.

Options:
    --only <id,id>   probe just these sources
    --timeout <s>    per-request timeout (default 45)
    --workers <n>    concurrent requests (default 6)
    --outdir <dir>   where to write results (default: alongside this file)

Optional credentials, read from the environment. Without them the four
credentialed sources are liveness-probed unauthenticated instead:
    NASA_API_KEY  SPACETRACK_USER  SPACETRACK_PASS  DISCOS_TOKEN  AMS_API_KEY

Generated by tools/bundle.py — edit the repo, not this file.
"""

from __future__ import annotations

import argparse
import gzip
import io
import json
import os
import pathlib
import ssl
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone

CATALOG = json.loads(r"""__CATALOG__""")
'''

    footer = '''

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Verify and rank space-hazard data sources.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--only", default="")
    ap.add_argument("--timeout", type=float, default=45.0)
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--outdir", default=str(pathlib.Path(__file__).resolve().parent))
    args = ap.parse_args()

    out = pathlib.Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)
    raw = out / "verification-latest.json"
    ranking = out / "ranking.json"
    report = out / "SOURCES.md"

    rc = _verify_main(
        ["--catalog", "-", "--out", str(raw), "--only", args.only,
         "--timeout", str(args.timeout), "--workers", str(args.workers)]
    )
    if rc:
        return rc
    print()
    rc = _rank_main(
        ["--catalog", "-", "--results", str(raw),
         "--out-json", str(ranking), "--out-md", str(report)]
    )
    print(f"\\nwrote {report}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
'''

    body = header.replace("__CATALOG__", json.dumps(catalog)) + verify_src + "\n" + rank_src + footer
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    OUT.chmod(0o755)
    compile(body, str(OUT), "exec")
    n_src = len(catalog["sources"])
    n_ep = sum(len(s["endpoints"]) for s in catalog["sources"])
    print(f"wrote {OUT} ({OUT.stat().st_size:,} bytes, {n_src} sources, {n_ep} endpoints)")


if __name__ == "__main__":
    main()
